version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/standard-jobs-range-behat-npm.yml

env:
  global:
    - REQUIRE_RECIPE_TESTING="^2"
    - REQUIRE_FRAMEWORKTEST="^0.4.2"
    # used by behat-extension LoginContext which expects a screen to choose
    # either topt or webauthn
    - REQUIRE_EXTRA="silverstripe/webauthn-authenticator:^4"
